name: Sync backend to GitLab

on:
  push:
    paths:
      - 'Backend/MonoF1_Ktor/**'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Backend to GitLab
        run: |
          git subtree split --prefix=Backend/MonoF1_Ktor -b gitlab-sync
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_USERNAME }}/monof1-backend.git
          git push gitlab gitlab-sync:main --force
